### ISSUE TITLE
MappingEditor: Add "delete mapping" button

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#114]
As provided in the MappingBrowser

**Comment by stefandesu** [comment]
There are problems with this very similar to #115, but I'm sure we can find a solution. Also, I think we'd also need a "clear mapping" button that just removes the mapping from MappingEditor.

**Comment by nichtich** [comment]
"clear mapping" is equivalent to "new mapping" but there can also be "reset/reload mapping". There are at least the following states and possible buttons:

* new and empty (no buttons)
* new and non-empty (save, new)
* loaded/imported and unchanged (delete, new)
* loaded/imported and changed (save, delete, reset, new)

In addition a non-empty mapping can be equivalent to another mapping or occurrence, but this is independent.

**Comment by stefandesu** [comment]
That sounds reasonable.

How about the case when a mapping was loaded, but one of the sides was completely replaced (which would make it not unlikely that the user is trying to create a new mapping). Should we show a small popup asking whether to override the mapping or create a new one?

> In addition a non-empty mapping can be equivalent to another mapping or occurrence, but this is independent.

When saving, we could also ask whether to override the existing mapping or to save it as a new mapping.

All of this gets even more complicated because a user might be logged in or not, or might have rights to edit mappings or not...

**Comment by stefandesu** [comment]
The delete button has now been added in the latest dev. I played around a bit and implemented it a bit differently. Could you take a look if that's okay, @nichtich?

**Comment by nichtich** [comment]
Works so far. The rest to do in the toolbar is part of #115.
