### ISSUE TITLE
MappingEditor: Indicate whether a mapping has been edited and not saved yet

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#115]
Given a mapping has been saved. If then the mapping is modified (e.g. change the mapping type) it should be visible as modified. 

* [x] grey out "save" icon if nothing has been changed
* [x] visual indicator if mapping has been changed

Probably requires #73. The issue is complicated because several kinds of changes are possible and it depends on whether the mapping has an URI or not.

**Comment by stefandesu** [comment]
I agree that MappingEditor should behave more like an actual editor. Currently there is not really a connection to the mappings already in the MappingBrowser.

> Probably requires #73. The issue is complicated because several kinds of changes are possible and it depends on whether the mapping has an URI or not.

I'm not sure #73 has anything to do with this (or maybe I still misunderstood that issue). Also, do you mean by "has an URI" that it has an identifier in general? Currently, I calculate the identifiers for all mappings that are loaded anyway, so this wouldn't be an issue. The issue is more that we have to keep track of the original mapping if the mapping is changed in a way that changes the identifier. I guess that's what you meant by "The issue is complicated because several kinds of changes are possible".

**Comment by stefandesu** [comment]
This is now partly implemented in the latest dev. Do you have a suggestion for a visual indicator that clearly shows that the mapping has been changed from the original?

**Comment by nichtich** [comment]
The "edit mapping" icon could be used. It's not perfectly easy but the same button at other places will reload the original mapping. I'd also change to order of icons:

* clear
* export/link (this might actually be one)
* *visual separator, e.g. whitespace*
* reset (with edit button)
* save
* delete

**Comment by stefandesu** [comment]
I'm not sure I understand what you mean. So the reset button would basically discard the changes you made to the mapping and set it back to the original? But it would have the edit icon? That doesn't make any sense.
