### ISSUE TITLE
MappingBrowser: include reverse mappings

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#118]
Select two concepts A and B, save as mapping, so the mapping is shown in the mapping browser. Then swap sides. The saved mapping is not shown anymore but it should be, no?

**Comment by stefandesu** [comment]
This definitely makes sense I think. I always thought that it's kind of weird that only mappings from left to right are shown. It's just more apparent when using the swap sides button.

Question: How should reverse mappings be displayed: Should the concepts be reversed or just the arrow? I'd say the latter because the sides would still match, but it could cause confusion with broader/narrower matches.

**Comment by stefandesu** [comment]
This is now implemented, but there are some small design questions associated with this:

1. If you go to DDC 612.112 on the left side, you'll now see 4 mappings, two from DDC to RVK and two from GND to DDC. For those latter two mappings, should concept DDC 612.112 be highlighted like it is in the first two mappings? (I'd say yes)
2. Same example, should for the latter two mappings the concept DDC 612.112 be clickable to be opened on the left side? So far, clicking on concepts in the `from` columns opens the concept on the left side, clicking on concepts in the `to` columns opens the concept on the right side. In this case, it is irrelevant because the concept is already selected anyway, but it might be relevant in other cases.
3. Should there be an option to only show mappings in one direction?

**Comment by nichtich** [comment]
1. yes, the selected concept should be highlighted everywhere

2. yes, all concepts should be clickable (see also #129) but it might make sense to add more intelligent heuristic at which side to open a clicked concept:

    * if concept is clicked right (`to`)
        * if it's scheme is opened left, select concept at the left (e.g. reverse mappings)
        * otherwise select at the right, possible switching scheme at the right
    * otherwise (`from` concept)
        * if corresponding target scheme is opened left, select concept at the right, possible switching scheme at the right (e.g. reverse mapping)
        * otherwise select concept at the left, possible switching scheme at the left

    The last can be tested by locally saving a mapping from GND to RVK and then switching the left scheme from GND to DDC.

3. yes but it's hard to name this option

**Comment by stefandesu** [comment]
Okay. I actually had similar thoughts about how to handle 2. at some point.

**Comment by nichtich** [comment]
An option to only show mappings in one direction is connected to an option to only show mappings that involve the concept at the left. In summary we have four options to control *direction*:

* [ ] show mappings from concept at the left
* [ ] show mappings to concept at the left (reverse mapping)
* [ ] show mappings to concept at the right
* [ ] show mappings from concept at the right (reverse mapping)

Not all 16 combinations of these options make sense.

**Comment by stefandesu** [comment]
I added a new setting "reverse" that can be used to show/hide reverse mappings. Now there are still two questions remaining:

1. How should the option be named? (Is "reverse" okay for now?)
2. Are there any combinations (out of the 16 you mentioned) that make sense but are not covered by the current options? Right now, we have 4 different options: show all schemes and show reverse, show all schemes and don't show reverse, don't show all schemes and show reverse, don't show all schemes and don't show reverse.

**Comment by nichtich** [comment]
It's ok to start with "reverse" and 4 possible cases to select.

**Comment by stefandesu** [comment]
Should we close this issue for now?
