### ISSUE TITLE
MappingEditor: add "share mapping" link with link shortener

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#126]
See http://tinyurl.com/y7nvjgm9 for an example (click "Link" icon on the right). URL shortening should be placed in an iframe like this:

* https://github.com/wikimedia/wikidata-query-gui/blob/c4c1161108e6a321c7ef949ad4266bb076e8dd06/wikibase/queryService/ui/App.js#L656

Base URL of link shortener can be a new config field, so link shortener will only be used if configured:

   "linkShortener": "https://tinyurl.com/api-create.php?url="

https://tinyurl.com/api-create.php?url=http://example.org/

**Comment by stefandesu** [comment]
It would be nice to have a copy-to-clipboard function with this as well, but that is not possible with an iframe. How about loading the content via AJAX instead?

Edit: This was obviously a stupid idea. AJAX is not possible in this case due to cross-origin policy. We'd need an actual URL shortener API with access token etc. to do this.

**Comment by stefandesu** [comment]
I only now noticed that you suggested this only for MappingEditor. I started implementing this globally with a button in the navbar. Right now, the selected schemes need to be shared anyway because MappingEditor won't be shown if no scheme is selected. What do you think about implementing this as a button in the navbar?

![kapture 2018-08-22 at 15 41 44](https://user-images.githubusercontent.com/3275148/44466960-ed4a4800-a621-11e8-8c9e-69172e4286af.gif)

**Comment by nichtich** [comment]
Link shortening can also be done outside of the application, e.g. by browser plugins. Better postpone this request.

**Comment by stefandesu** [comment]
> Link shortening can also be done outside of the application, e.g. by browser plugins. Better postpone this request.

I agree, but what you can see in that image above is already implemented in a separate branch, so we could just put it in and look for a long-term solution later. What do you think?

**Comment by nichtich** [comment]
This does not solve a relevant use case but adds a non-navigational function to the navbar so I'd prefer not to enable it.

**Comment by stefandesu** [comment]
Got it. 👍
