### ISSUE TITLE
Create Skosmos-API wrapper

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#142]
Or add JSKOS support to Skosmos. This is important to support a much larger number of terminologies, see https://bartoc-skosmos.unibas.ch/en/ and http://zbw.eu/beta/skosmos/stw/ among others. See also https://bartoc-fast.ub.unibas.ch/bartocfast/about for a list of public Skosmos instances (and a federated search on them). API documentation is available at http://api.finto.fi/doc/

**Comment by nichtich** [comment]
We could start with STW (via http://zbw.eu/beta/skosmos) to support our colleagues at ZBW.

Access to individual vocabularies vis Skosmos should be configured in Cocoda, e.g.

~~~json
{
  "provider": "SkosmosApi",
  "api": "http://zbw.eu/beta/skosmos/rest/v1/",
  "schemes": [ {
    "uri": "http://bartoc.org/en/node/313",
    "VOCID": "stw"
  } ]
}
~~~

So Cocoda could build queries such as `{api}{VOCID}?lang={lang}` to get information about a vocabulary and `{api}{VOCID}/data?uri={uri}&format=application/json` to get all information about a concep. Examples:

* http://zbw.eu/beta/skosmos/rest/v1/stw/?lang=de
* http://zbw.eu/beta/skosmos/rest/v1/stw/data?uri=http://zbw.eu/stw/descriptor/19626-5&format=application/json

There are [other concept related queries](http://api.finto.fi/doc/#/Concept-specific_methods) but `/data` is enough to start with.

Top concepts and concept types do not need to be supported from the beginning but we need [search via Skosmos](http://api.finto.fi/doc/#!/Vocabulary-specific_methods/get_vocid_search). The search URL pattern is '`{api}{VOCID}/search?query={query}*&unique=1`. Example:

* http://zbw.eu/beta/skosmos/rest/v1/stw/search?query=Fisch*&unique=1

**Comment by stefandesu** [comment]
Too bad you can only request concept scheme labels in one language at the same time. For concepts on the other hand, all labels are returned in one `/data` request.

**Comment by nichtich** [comment]
> Too bad you can only request concept scheme labels in one language at the same time.

For popular vocabularies we may don't need the information anyway as it should be included in kos-registry via Wikidata, BARTOC or `kos.yaml`. `kos-registry.json` could be linked as static file to Cocoda config

**Comment by stefandesu** [comment]
> For popular vocabularies we may don't need the information anyway as it should be included in kos-registry via Wikidata, BARTOC or `kos.yaml`. `kos-registry.json` could be linked as static file to Cocoda config

Good point.

**Comment by stefandesu** [comment]
I added a first implementation of the Skosmos wrapper with STW as an example. Note that their API seems to have some issues currently, but in general it should work (no top concepts, but loading concepts and suggest work).

Some caveats/further tasks:
- [x] Currently there are no API URLs in DataModal for STW concepts. The problem is that ItemDetail generates these links per concept based on the registry's `/data` endpoint. The problem is that in this case, the registry's `/data` endpoint depends on the vocabulary. I will find some solution for this eventually. ~~*Edit: The `/data` endpoint also exists as a global endpoint on Skosmos instances, so we can use that for API URLs. 👍*~~ ~~Edit 2: The global `/data` endpoint doesn't return anything for concepts...~~ Edit 3: Solved it differently.
- [x] The wrapper loads broader and narrower concepts via `/data` (they are included in the response) which works very well. But Cocoda has some assumptions about the relation between `narrower` and `ancestors` that sets a concept's `ancestors` property which causes Cocoda not to show its broader concepts anymore. This has to be fixed as well.

**Comment by stefandesu** [comment]
Right now, it doesn't seem to work in dev at all, although it still works fine locally. I'll investigate.

**Comment by stefandesu** [comment]
Such an obvious error. It works now, so feel free to test.

**Comment by stefandesu** [comment]
Create new specific issues for missing functionality if necessary.
