### ISSUE TITLE
Support concept schemes without notations

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#154]
For instance [this concept scheme](https://gbv.github.io/cocoda/dev/?fromScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Freligion%2F) and [this example mapping](https://gbv.github.io/cocoda/dev/?fromScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Freligion%2F&toScheme=http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F430&to=http%3A%2F%2Fd-nb.info%2Fgnd%2F1124103031&mapping=%7B%22from%22%3A%7B%22memberSet%22%3A%5B%7B%22uri%22%3A%22http%3A%2F%2Furi.gbv.de%2Fterminology%2Freligion%2F62917285-3b20-4616-b7d7-3715b9dac124%22,%22notation%22%3Anull%7D%5D%7D,%22to%22%3A%7B%22memberSet%22%3A%5B%7B%22uri%22%3A%22http%3A%2F%2Fd-nb.info%2Fgnd%2F1124103031%22,%22notation%22%3A%5B%221124103031%22%5D%7D%5D%7D,%22fromScheme%22%3A%7B%22uri%22%3A%22http%3A%2F%2Furi.gbv.de%2Fterminology%2Freligion%2F%22,%22notation%22%3A%5B%22RELIGION%22%5D%7D,%22toScheme%22%3A%7B%22uri%22%3A%22http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F430%22,%22notation%22%3A%5B%22GND%22%5D%7D,%22type%22%3A%5B%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23mappingRelation%22%5D%7D&identifier=urn%3Ajskos%3Amapping%3Acontent%3A0a93840b3fbd5571cd6cc6bb855d6252a03de5c6).

**Comment by stefandesu** [comment]
In theory, there should be no problems with concepts without notations. Specifically with "Diskordianismus", there seems to be an error in DANTE, see the URI of the first concept of [this request](http://dev-api.dante.gbv.de/narrower?uri=http://uri.gbv.de/terminology/religion/88c7866c-74a4-47ba-8ae4-01a57bc5ad00). But we do need a way to display mappings that include concepts without notations. I guess instead of the notation, we just display the (potentially truncated because of length) prefLabel?

**Comment by stefandesu** [comment]
Question regarding your second example:

The mapping that is loaded from the server is actually a WIKIDATA - GND Mapping (it's showing the concept schemes on my local machine, not sure why it's not showing on dev), and that particular Wikidata concept on the left side DOES have a notation which is `Q7340`. Interestingly, it is not loaded on your link because the [query with only the `to` parameter](http://coli-conc.gbv.de/services/wikidata/mapping?to=http:%2F%2Fd-nb.info%2Fgnd%2F1124103031) does not return a notation for the `from` side. If you actually select that concept on the left side (currently not possible because no notation is shown), a [different query with only the `from` parameter](http://coli-conc.gbv.de/services/wikidata/mapping?from=http:%2F%2Fwww.wikidata.org%2Fentity%2FQ7340) includes the notation (for both sides). Also, the [query for the detail data of that concept](http://coli-conc.gbv.de/services/wikidata/concept?uri=http:%2F%2Fwww.wikidata.org%2Fentity%2FQ7340&properties=uri,prefLabel,notation,inScheme,identifier,altLabel,definition,license,publisher,created,issued,modified,scopeNote,editorialNote&language=de) doesn't return a notation either.

**Comment by stefandesu** [comment]
My second comment doesn't have anything to do with this particular issue, and prefLabel was now added as a fallback for ItemName, so I'm closing this issue.
