### ISSUE TITLE
Switch concept scheme from MappingEditor

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#164]
If the MappingEditor uses concepts from a concept scheme not selected, this schem(s) are shown above the concepts. Make this name clickable to select the concept scheme left/right.

**Comment by stefandesu** [comment]
I don't think this is really necessary. On the left side, the concept scheme is already determined by the concepts that are on that side, and it will change automatically when replacing the concept with one from a different scheme. On the right side, we have two cases:

1. There are concepts on the right side. In this case, changing the concept scheme doesn't make sense because the concepts belong to that scheme. Adding a concept from a different scheme will override the whole right side.
2. It's a mapping with no target concepts. In this case, the target scheme of the mapping changes according to the selected target scheme. And I don't think it makes sense to create e.g. a DDC to BK mapping without target concepts in BK if RVK is actually selected on the right side.

**Comment by stefandesu** [comment]
Please ignore that issue that references this one, I pasted the wrong thing and the note here stays even though I removed the reference.
