### ISSUE TITLE
DANTE Suggest: Notations are not shown in front of labels

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda#277]
When searching the RVK, the notation is unknown and there are too many results with the same name.
A solution could be to implement a mouse-hover function, which shows the notation of the results.
Ex.: Blut

**Comment by stefandesu** [comment]
The notation is actually supposed to be there, so this seems to be a bug. When you search for a notation, the notations are actually included for all result. I'll take a closer look tomorrow to see whether it's a bug in Cocoda or in DANTE.

We're also hoping to improve the RVK results by removing all synthetic concepts, so that there won't be 50 times "Blut, Blutbildungszentrum, Milz, insgesamt" or something.

**Comment by stefandesu** [comment]
As far as I understand, this is either a bug or missing feature (if the current behavior is intended) in DANTE. I've notified the person in charge.

**Comment by stefandesu** [comment]
I removed the milestone as it is not in our control.

**Comment by stefandesu** [comment]
Fixed in DANTE now!
