### ISSUE TITLE
TheSettings/MappingBrowser: clarify possible setting

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#298]
Setting in the MappingBrowser:

* [ ] Show results of all concept schemes
          
Setting in TheSettings:

* [ ] Always show all mappings and suggestions in mapping browser

Is this the same then why different labels. If not, why not include both at both places? See also #297.

**Comment by stefandesu** [comment]
> Show results of all concept schemes

Means it will show mappings even though the target scheme does not necessarily matches the selected target scheme.

> Always show all mappings and suggestions in mapping browser

Means that there won't be any more "..." to expand results, but all results are always shown.

The reason that the second one is in TheSettings is because when it was added, MappingBrowser didn't have the settings thing yet. I think it would be better to move all MappingBrowser-related settings to MappingBrowser.

**Comment by stefandesu** [comment]
I moved the setting from TheSettings to MappingBrowser and added an explanation via tooltip (just like for the other setting).
