### ISSUE TITLE
Wrap MappingTable in MappingBrowser

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#31]
The purpose of this component is to show existing concordances, mappings and mapping recommendations. A table is just the primary form to display mappings. A MappingBrowser would also allow browsing in concordances and selection of sources where recommendations should come from.

**Comment by nichtich** [comment]
The middle part of the whole cocoda application could be structured with components like this:

~~~
MappingTool { 
  MappingEditor, 
  MappingBrowser { 
    MappingTable
  }, 
  OccurrencesBrowser {
    OccurrencesTable
  }
}
~~~

This would also solve issue #30.

**Comment by stefandesu** [comment]
Right now, it doesn't really make sense to separate MappingTable from MappingBrowser or OccurrencesTable from OccurrencesBrowser because it's a mostly unmodified bootstrap-vue table. Depending on which functionality will be implemented in MappingBrowser and whether the table will be used elsewhere we could reopen this issue, but at this point I think it's sufficient that the table is directly in the browser. 

The CSS for the tables is already in the global file, so there's no duplication there.
