### ISSUE TITLE
Identity: Namechanges do not get applied to mappings

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda#326]
If you edit and save a mapping, it shows your name as the creator.
But when changing your Name the changes do not get applied to the saved mapping, the name stays the same as before, although it ought to have changed.

**Comment by stefandesu** [comment]
This is actually a new feature, not something that was supposed to happen (as you say). Currently, there is a button `Settings -> Local Mappings -> Rewrite creator for all local mappings` which does exactly what you want. If @nichtich agrees, we can do that automatically for every change in the identity. 

Note that this would only apply for **local** mappings. Theoretically, we could implement a method in `jskos-server` to batch rewrite mapping creators, but it's not there yet.

**Comment by nichtich** [comment]
It's a usability issue: If user X has saved a mapping in jskos-server, later changes his name and opens the same mapping than:

* the mapping editor shows the new name but the mapping cannot be saved
* the mapping browser shows the mapping with old (currently in jskos-server) name

How should a user know how to change the name in jskos-server? The name mismatch should be indicated somehow, and re-saving of the mapping should be possible, no?

**Comment by stefandesu** [comment]
@nichtich What you're describing is different from how I interpreted @DennisTobola's issue. You're right: It should be possible to save a mapping if only the name has changed. But that requires deeper changes in Cocoda because currently it is using the identifier which doesn't seem to include the creator (or there's some other bug). But in any case, that's something that is solvable relatively easily.

How I interpreted the original issue was that when I go to settings and change my name, all my existing mappings will automatically get the new name associated with them. For local mappings, that would be the same as "Rewrite creator for all local mappings" in settings, just for every name change. For remote mappings, we'd need to have a way to batch rewrite the creator for potentially lots of mappings.
