### ISSUE TITLE
ConceptDetails: selected tab should be kept when switching concepts

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#331]
1. select a concept
2. in ConceptDetail select a tab, e.g. "Search Links"
3. select another concept

The open tab is always switched to the first tab. It should stay at the selected tab instead.

**Comment by stefandesu** [comment]
The tab system in ConceptDetail has to be reimplemented anyway. The provided component that we use from bootstrap-vue is so weird that we can't even reliably set the order of tabs (probably because tabs appear and disappear depending on what info is there, and some things are loaded in the background so they appear only after a while, etc.).

**Comment by nichtich** [comment]
When implementing the tab systems, it could also be extended accordion view (vertically stacked) if there is enough space. Especially if the ConceptTree window is closed, it should be possible to open multiple tabs at the same time instead of selecting only one. See [this article](https://uxdesign.cc/little-things-in-ux-design-part-1-tabs-v-s-accordions-47390e4910c3) for dome design guidelines when to use tabs vs. accordion.
