### ISSUE TITLE
Add button and keyboard shortcut to add left & right concept to current mapping

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#332]
Maybe Ctrl + y because its between a and s in QWERTY layout (Ctrl + w would also do but it closes the browser windows by default so better don't use this). The button could look like the normal circled (+) on each side.

**Comment by DennisTobola** [comment]
Aren't there already shortcuts for said issue?
Ctrl + a adds the left concept, if selected.
Ctrl + d adds the right concept, if selected.

Settings page - keyboard-shortcuts
Linkes Konzept zu aktuellem Mapping hinzufügen
Ctrl + a oder Cmd + a

Rechtes Konzept zu aktuellem Mapping hinzufügen
Ctrl + d oder Cmd + d

**Comment by stefandesu** [comment]
@DennisTobola This issue is about adding both left and right concept to the mapping at the same time. Basically combining the two existing shortcuts into one. I don't have anything against it, but I also think that it's a little unnecessary, and I also think using a shortcut that's specific for one keyboard layout is not the best option.

**Comment by stefandesu** [comment]
Suggestion: Ctrl/Cmd + b (for "both").
