### ISSUE TITLE
BK uses ICONCLASS, RVK, and BK

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda#334]
Well, here we go again.
Here is a link, where i searched the BK for "Al" and got results from ICONCLASS.
https://coli-conc.gbv.de/cocoda/dev/?fromScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F&from=http%3A%2F%2Ficonclass.org%2F92H57 

After further investigation and by searching "Allgemeinb" I got 3 results:
*  01.11 Allgemeinbibliographien. Universalbibliographien (BK!)
*  QX 860 Allgemeinbildende Schulen (Sekundarstufe) (RVK)
* AA 50000 - AA 99500 Internationale Allgemeinbibliografien, Nationalbibliografien, umfassende Buchhandelskataloge (RVK)

But take note, that such results are the minority, after searching "national" I got pretty much ICONCLASS only results.

**Comment by stefandesu** [comment]
Once again, this was a problem with DANTE's cache, having cached the old results before fixing the issue. I deleted the DANTE cache and it should be fixed for all cases. The next time you find something like this, let me know directly without creating an issue because it has nothing to do with Cocoda. ;)

**Comment by DennisTobola** [comment]
Ok, I'll let you know next time.
