### ISSUE TITLE
MappingEditor: better indicate notation and scheme

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#339]
The MappingEditor should differentiate notation and label with typography and always show which schemes are currently mapped between.

![image](https://user-images.githubusercontent.com/299856/57071743-aeee4800-6cdb-11e9-99ff-38e6f7f2b069.png)

![image](https://user-images.githubusercontent.com/299856/57072204-338d9600-6cdd-11e9-9dcf-db7cd038b44f.png)

**Comment by stefandesu** [comment]
This should be a VERY easy fix.

1. The label is only bold when that concept is selected on one side. We could remove that so that we always have the differentiation between notation and label.

2. Concept schemes are already there, but hidden when the same scheme is selected on that side. We can just not hide it.
