### ISSUE TITLE
Define default placeholder for each component

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#34]
Components are empty when the application is started, for instance if no concept scheme has been selected (all components) or if no concept has been selected (occurrences). A default contect should be shown for instance a welcome message and/or brief introduction what to do.

**Comment by stefandesu** [comment]
228d7f68cf834222b50a62ee4a2fc43d87c8cbb7 hides the content of the mapping components and shows a welcome message. In the current state of the project, it is not trivial to display a placeholder instead of the component, mainly because of the complexity of the resizing functionality. 

To add to the suggestion, on the left and right side there could be a list of commonly used schemes for quick selection.

**Comment by stefandesu** [comment]
One reason why this isn't trivial to do is because the "main" components (meaning ConceptDetail, ConceptTree, MappingEditor, MappingBrowser, and OccurrencesBrowser) are all nested inside another component (ConceptSchemeBrowser and MappingTool). Would it maybe make sense to structure the project like this:

```
App {
  TheNavbar
  SchemeSelector (or different name)
  ConceptSearch
  ConceptTree { ... }
  MappingEditor
  MappingBrowser
  OccurrencesBrowser
  SchemeSelector
  ConceptSearch
  ConceptTree { ... }
  TheFooter (we don't have this right now, but it might make sense at some point)
}
```

Of course, we'd put a lot more logic into App, but then things like component placeholders and resizing of components (#32) would be in one central place. This would also simplify communication between components.

**Comment by stefandesu** [comment]
Done with 5008f36f7011d40ab609ca45db6fdadd5e1ee9fb.
