### ISSUE TITLE
Validate config file

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#353]
In addition to #352 add JSON Schema to validate the configuration file. To avoid re-adding full JSON Schema support try <https://github.com/epoberezkin/ajv-pack>.

**Comment by stefandesu** [comment]
Even with ajv-pack, we would need to add `ajv` as a dependency (although supposedly Webpack only takes a single necessary method out of it and it wouldn't add that much bloat).  

I'll move this to a later milestone. I would also suggest either just adding a "manual" validation method (that only looks at properties and types), or adding a proper JSON Schema, but only add validation to the build script. The latter wouldn't be very effective though because most people who install their own Instance of Cocoda would probably use the already built files and adjust the configuration directly.

**Comment by stefandesu** [comment]
Also related to #549.
