### ISSUE TITLE
MappingSearch: limit search by registry

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#359]
The mapping search tab of mapping browser should also allow to toggle registries like possible in mapping navigator.

**Comment by stefandesu** [comment]
This is on my list, the question is: How do we add this without taking up even more space? My idea was to add a registry filter next to the concordance filter, but then you'd only be able to select either one or all registries. Another idea would be to add only the registry notations to select and deselect just like the Mapping Navigator. Because only the Available Mappings are relevant, this wouldn't take up much space and could easily fit in the same row as the concordance filter.

Another question: Should this selection be the same as in Mapping Navigator? I.e. if I disable local mappings in Mapping Search, should it be disabled in Mapping Navigator as well? If yes, this would make it much easier to implement.

**Comment by nichtich** [comment]
Putting it next to registry seems best and the icons as toggle buttons are enough. Coupling the selection with mapping navigator makes sense also for usage.

**Comment by stefandesu** [comment]
This is now added to the test instance. Should we also add a label "Registries:" in front of the list of icons, or do you think it's clear enough like this?

**Comment by nichtich** [comment]
The mapping search is expert search and a label would not add enough information anyway so keep it as it is.
