### ISSUE TITLE
Preserve the current state of the application

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#36]
Client-side (in-browser) storage could be used to preserve the current state of the application even after refreshing the site or restarting the browser. See https://vuejs.org/v2/cookbook/client-side-storage.html.

**Comment by nichtich** [comment]
The current state could also be stored in the fragment identifier as part of the URL (https://coli-conc.gbv.de/cocoda/#hercomesthestate), see [shared state and routing in vue](https://codeburst.io/shared-state-and-routing-in-vue-js-7bfea06e44ec). Client side storage could also be used for caching and as private backend to store mappings - but that's another issue. The question of this issue is:

What is part of the "current state of the application"?

- which concept schemes are selected (yes)
- which concepts are selected in each concept scheme (yes, at least one side)
- selected mapping (?)
- state of mapping editor (no?)
- current size of the components (no)
- additional configuration, e.g. selected language of user interface (irrelevant as not supported yet)
- ...

**Comment by stefandesu** [comment]
We should use [Vue Router](https://router.vuejs.org) for this. It would make sense to use URL query parameters for the selected schemes/concepts and the current mapping. Here is a relevant tutorial: [How to make content dynamic via URL query parameters in Vue](https://medium.com/@BjornKrols/tutorial-dynamic-content-via-url-query-parameters-in-vue-js-d2df19b66633).

**Comment by stefandesu** [comment]
Selected concept schemes and concepts are now added as URL parameters (`schemeLeft`, `conceptLeft`, `schemeRight`, `conceptRight`). Leaving this issue open for further discussion and ideas.

**Comment by stefandesu** [comment]
The current mapping in MappingEditor should be part of the URL parameters as well.

**Comment by stefandesu** [comment]
The current mapping is now part of the URL parameters, although with a few caveats:
- Only supports one mapping type.
- Only supports memberSet.
- Only supports single members in memberSet.
- The mapping object will contain the full objects (for schemes and concepts) after a page reload, not just the necessary information. This might also lead to an URI change, e.g. if the mapping originally used BARTOC URIs for schemes.

All of these except for the last point will be fixed later. I'm not sure if it's possible to actually fix the last point without encoding the whole mapping object. I'll think about it.

**Comment by stefandesu** [comment]
1. To fix all the caveats in the previous comment, we should encode the whole mapping object and put that into the URL parameter. Only thing is that we need to filter out all concept/scheme properties except for `uri`.
2. Today's commits feature settings in local storage. Part of this is also saving the sizes and minimized status for each component. This means that we basically achieved to preserve the full state of the application, although some of it is in the URL params (selected schemes and concepts, current mapping), and some of it in local storage (component sizes and minimized status).

Because of all this, I will (finally) close this issue. Number 1 will be implemented in the next few days.
