### ISSUE TITLE
Apply Unicode normalization to avoid trouble with Umlauts

### ISSUE THREAD

**Issue by annakasprzik** [gbv/cocoda#403]
Search terms containing Umlauts are truncated at the "a/o/u", see screenshot
![Antipa](https://user-images.githubusercontent.com/25246212/58948619-cad98380-878a-11e9-8ea1-4f65e965926f.PNG)

**Comment by stefandesu** [comment]
After further investigation, I've found out that the Umlaut that the GND API returns seem to be non-standard. A normal `ä` is encoded as `%C3%A4`, while the ä from GND (actually `ä` which is a different character) is encoded as `a%CC%88` (so I guess it's an `a` and the dots separately). That's also why it cuts off at `a` because it is separate from the dots (but if together, it is shown as `ä`).

I'll think about a way to deal with this, probably some kind of unicode normalization.

**Comment by nichtich** [comment]
All incoming JSON data should be normalized to NFC [as specified in JSKOS spec](https://gbv.github.io/jskos/jskos.html#data-types).
