### ISSUE TITLE
Link to end-user manual

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#436]
`npm run user-manual` creates end-user manual in HTML but the HTML files are only copied to `dist/` so they don't end up at http://coli-conc.gbv.de/cocoda/dev/user-manual-de.html, http://coli-conc.gbv.de/cocoda/dev/user-manual-en.html where they should. When this is fixed, the README and the Help link in menu bar should link to end-user-manual.

**Comment by stefandesu** [comment]
1. For the manual to be accessible in dev, `npm run user-manual` must be added to the webhook that builds the dev.

2. For the manual to be accessible in the build release on GitHub, `npm run user-manual` must be put after `npm run build` because `dist` is moved after that. 

The question is whether this is really what we want. Wouldn't it be enough if the manual was accessible on GitHub Pages via https://gbv.github.io/cocoda/user-manual-de.html? In that case we'd need to change the Travis config as well because the file would need to be included in the styleguide folder.

Edit: An argument for having the manual right in the build would be that there might be changes to the manual that relate to changes in dev that are not yet pushed to master, so someone using the release instance might get confused by reading the (newer) manual from dev.

**Comment by nichtich** [comment]
* [x] Link to user-manual from README
* [x] Link to user-manual from "Help" menu item (replace with hard-coded "Anleitung" / "Manual")
* [x] extend user-manual to include build time and version number
* [x] Fix link from the welcome page

At least the [German manual](https://gbv.github.io/cocoda/dev/user-manual-de.html) should also be proofread and some screenshots can be updated.

**Comment by nichtich** [comment]
The date and version from `build-info.json` are included in the manual but they only show up when this file actually contains non `null` values.
