### ISSUE TITLE
Add meaningful error message if backends are not reachable

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#437]
If login-server is down, the whole applications does not start up. There should be a timeout and an error message indicating which service is not reachable and a fallback to disabling the non-reachable registry or login-server.

**Comment by stefandesu** [comment]
Definitely agree that backend outages need to be handled in a better way.

> If login-server is down, the whole applications does not start up.

This does not happen for me (using a local login-server instance), are you sure this is the case?

**Comment by stefandesu** [comment]
This can be implemented after #536. Having a central place which manages all API requests, we can add error handling there (maybe together with a Vue mixin that deals with showing the error in the UI if necessary). We can differentiate between requests that fail silently (console only) and those which fail with an error message, and we could also add something like a status indicator which shows which registry is having issues. I feel like this is going to be a bit more complicated. 😅

**Comment by stefandesu** [comment]
I might have to tackle this together with #522 because I need to add error handling for cocoda-sdk anyway, so I can as well do it properly.

I would suggest separating backend errors into three categories:

1. Errors on user actions. When the user is actively doing something (e.g. saving or deleting a mapping), and it fails, Cocoda should always show a message, if possible including the reason for why it didn't work.

2. Errors in Mapping Browser: I would handle errors in Mapping Browser differently. My suggestion would be an additional error symbol in the header of a registry section if there was an error loading mappings from that registry. We don't need to actively show these errors in my opinion.

3. Errors for other background tasks. Here, I would suggest showing the first error that occurs for a certain registry, and then silently handle further errors. Maybe there could be some kind of timeout after which another error is shown or something. We could also show one error per registry per error type or something.

What are your thoughts, @nichtich?

**Comment by nichtich** [comment]
I fully agree with separation between 1 and 2 but I don't quite understand 3. Maybe an error indicator at the top menu to indicate some background loading failed?

**Comment by stefandesu** [comment]
That's a much better idea! 👍

**Comment by stefandesu** [comment]
The error messages are still not optimal, but much better than before, especially for a network outage or server issue. Therefore, I consider this issue closed. Improvements can still be added over time.
