### ISSUE TITLE
MappingNavigator: Filter reconciliation sources

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#449]
Add an option to hide mappings suggested from reconciliation if they are already stored in the current mapping registry. Example:

![image](https://user-images.githubusercontent.com/299856/63260284-c3515300-c280-11e9-9dd4-a1eb56726c90.png)

The mapping from Q1144457 Quantenphysik to GND 4266670-3 Quantenphysik is shown twice without the suggested filter option.

**Comment by stefandesu** [comment]
The same applies for all other recommendations, right? It would be easier to implement this for the whole group of registries.

Also, they will only be hidden if they already exist in the currently selected registry, right? 

I would use the memberIdentifier for this because the mapping type is not relevant.

**Comment by nichtich** [comment]
Yes, yes, and yes.
