### ISSUE TITLE
ConceptTree: highlight mapped concepts

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#458]
Mapping a whole classification or part of it requires some better way to see which concepts have been mapped and which have not been mapped yet. A simple approach could be this:

If a concept scheme is selected on both sides. For all concepts in a ConceptTree do a query for mappings from the concepts shown to concepts in the currently selected registry to the currently selected other concept scheme. If a mapping is found, highlight the concept label as bold as shown here for 17 and 20:

![image](https://user-images.githubusercontent.com/299856/63686856-4e8f9300-c803-11e9-9cfd-d0ec60485864.png)

This feature could be disabled/enabled in ConceptTree settings as it requires additional API queries that may slow down the application and for fully mapped schemes you don't always want to show every concept as bold.

**Comment by stefandesu** [comment]
- Use registry that is currently selected for writing.
- Load for all shown concepts (API request with limit=1).
- Refresh if mappings are loaded for example in Mapping Search/Navigator, but not periodically (too much overhead).
- Maybe use green dot instead of bold font.

**Comment by stefandesu** [comment]
I added a first implementation suggestion in dev, using a green dot on the right side of the item. Note that it's disabled by default and has to be enabled using the ConceptList settings.

Please check the following:

- Does it work as expected?
- Does it look good?
- Does it have a noticeable effect on performance? (it shouldn't because it's just one request for all concepts on one side)

Known issues:
- If a mapping is deleted (either by the current user or on the server by another user), the status does not update. Meaning that if a concept is determined as "mapped" once, it will stay that way until the page is reloaded. This issue is difficult to solve (especially if the mapping is deleted on the server), but in practice it shouldn't really matter much. I will create a separate issue for this.
- It does work for the favorite concepts as well, but it doesn't always load immediately. I have to investigate.

Examples to test it with: Try [BK -> DDC, select Concordance Registry, and open "7-8 Sozialwissenschaften" on the BK side](https://coli-conc.gbv.de/cocoda/dev/?fromScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F&toScheme=http%3A%2F%2Fdewey.info%2Fscheme%2Fedition%2Fe23%2F&from=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F7-8). You'll see that some of the concepts have been mapped already. You can also select Local Mappings and create mappings between the systems.

**Comment by stefandesu** [comment]
This is currently not working when using Wikidata as a mapping registry. See https://github.com/gbv/wikidata-jskos/issues/45.

**Comment by stefandesu** [comment]
Since there is no change on Cocoda's side necessary for the Wikidata fix, I'll close this issue now.
