### ISSUE TITLE
TheSetting: add component settings

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#468]
Components have their own settings, available via a small popup. All these settings should also be available in TheSettings modal, grouped by component.

**Comment by stefandesu** [comment]
Any idea if there is a way to do this without duplicating every single component setting inside TheSettings?

**Comment by stefandesu** [comment]
I thought a little bit about this and I believe it would make sense to revamp the component settings.

1. Component settings should be defined in a central spot (e.g. Vuex store or separate JSON file) with the following properties:
  - name of component (e.g. "ItemDetail")
  - whether setting is dependent on `isLeft`
  - type of value (e.g. boolean or number)
  - default value
  - (possibly more properties, like minValue and maxValue for numbers)

2. Instead of using completely separate keys to save the settings in local storage, generate the JSON structure for saving the settings from the central definition.

3. Adjust `ComponentSettings` component to automatically generate the settings from the central definition for the current component.

4. Maybe add a mixin for component settings for easy access instead of having to go through Vuex. 
  - It might be possible to combine this with 3.

5. Then we can add a tab in TheSettings which fulfills the original requirements of this issue.

As you can see, this is getting a little bit more complicated than expected, but it would make it much easier to manage and add component settings.

**Comment by stefandesu** [comment]
@nichtich ~~This change would cause previous (component-related) settings to be lost. Would that be okay or should we implement some kind of migration of the previous settings? We could do what we've done in the past, which is to add migration code and remove the migration at a later point, e.g. the next minor update.~~ Edit: No migration.

**Comment by stefandesu** [comment]
Just to note it down here for later, this is how I imagine this:

```js
{
  ItemDetail: {
    showAllAncestors: {
      prefLabel: {
        en: "Always show all ancestors",
        de: "...",
      },
      type: Boolean,
      default: false,
      sideDependent: false,
    },
  },
}
```

Not sure about `sideDependent`, maybe it should be called differently. We could also add a description if necessary.

**Comment by stefandesu** [comment]
I finally started working on this properly and it's pretty complicated. I'm sure it will be worth it in the end, but it might take a while...

**Comment by stefandesu** [comment]
The biggest step is done, which is to revamp the component settings. These are now defined in `config/settings.json`. Because this was a huge change (way too many files in one commit, but it couldn't be done otherwise), this has be tested carefully. So if you have some time @nichtich, please test a little bit to see whether all settings still work as they are supposed to. Thanks!

Open tasks:
- [x] Test
- [x] Add component settings to Settings modal (as separate tab?)
- [x] Clean up if necessary (there might be unused bits in `locale.json` or other places)
- [ ] Add documentation on how to add new component settings and how to use them

**Comment by nichtich** [comment]
Looks good and seems to work as intended (tested at `dev` instance)!

**Comment by stefandesu** [comment]
I added the component settings to the "User Interface" tab in TheSettings. Is that okay @nichtich ? Should we maybe rename that tab, but still keep the interface language and the reset card size button in there? I don't think an additional tab would be a good idea because we don't have enough space for it on smaller screens.
