### ISSUE TITLE
Skip warning if config/cocoda.json not found

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#47]
If no `config/cocoda.json` exists a warning is thrown and `npm run dev` stops.

**Comment by stefandesu** [comment]
Unfortunately, with the way this is currently implemented, I couldn't find a way to do this. The problem is that we import the config file like a JS module (`require("../config/cocoda.json")`) and Webpack complains if we do anything with it that is not static. And for some reason, even though there is a try-catch block around the statement, the warning still get through (although `npm run dev` does not stop for me). I tried stuff like [optional-require](https://www.npmjs.com/package/optional-require) which also did not work (this results in a `critical dependency` warning that does stop `npm run dev` even on my machine). 

I can imagine that there is a way to fix this by dynamically injecting the config file into `src/config.js` on build, but so far I couldn't figure it out. I'm open to any suggestions!

**Comment by nichtich** [comment]
Moved to later with #49.
