### ISSUE TITLE
MappingBrowser: show scope note on hover

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#475]
When hovering a concept in the mapping browser, a concept's scope note (if available) should be shown. For instance [this example](https://coli-conc.gbv.de/cocoda/dev/?fromScheme=http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F1940&toScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F&to=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F56.23&mapping=%7B%22from%22%3A%7B%22memberSet%22%3A%5B%5D%7D,%22to%22%3A%7B%22memberSet%22%3A%5B%7B%22uri%22%3A%22http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F56.23%22,%22notation%22%3A%5B%2256.23%22%5D%7D%5D%7D,%22fromScheme%22%3Anull,%22toScheme%22%3A%7B%22uri%22%3A%22http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F%22,%22notation%22%3A%5B%22bk%22,%22BK%22%5D%7D,%22type%22%3A%5B%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23mappingRelation%22%5D%7D) shows several concepts with label "Brückenbau" in Wikidata Reconciliation. but to find out their meaning the scope should more easily be accessible.

**Comment by stefandesu** [comment]
I could imagine something like GitHub's popover for issues and users for ItemName. Maybe we could make it configurable which information is shown there.

**Comment by nichtich** [comment]
I welcome extended popover with more information in a nicer fashion but no configuration please.

**Comment by stefandesu** [comment]
I added a popover to ItemName. Please take a look and give feedback. My own thoughts:

- [x] Font sizes could be reduced (they are larger than our usual sizes).
- [x] I haven't found an example yet, but we should limit the size of the scope note so that the popover won't be impossibly large.

We could show more information as well, but we should be careful not to clutter it too much.
