### ISSUE TITLE
"next" button is scrolled

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#478]
If the concept detail component is scrolled, the "next" button does not stay at the bottom.

![image](https://user-images.githubusercontent.com/299856/64759204-cca7a580-d536-11e9-8d25-bdc9ffa2ef7d.png)

I'd rethink position of the button anyway. How about puttin it as arrow in the tabs?:

![image](https://user-images.githubusercontent.com/299856/64759506-928ad380-d537-11e9-9434-19ca5ccba6b5.png)

**Comment by stefandesu** [comment]
Should it be in every tab? 

At least I could find out why the button is scrolling with the rest. The other two buttons are in ItemDetail and outside of the itemDetail-content. Because the next button is defined in ConceptDetail, it is part of itemDetail-content and therefore scrolls as well.

If we anchored it either inside the tab content area or maybe right-align next to the tab headers, it would scroll as well, but it would make more sense.

**Comment by nichtich** [comment]
It should be in the info tab or in all tabs. Next to the tab headers would be confusing.
