### ISSUE TITLE
Add "prev" button

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#501]
In addition to the "next concept" button there should be a reverse "previous concept" button. Keyboard shortcuts could be [Alt+J](https://defkey.com/what-means/alt-j) and  [Alt+K](https://defkey.com/what-means/alt-k). If this takes more time to implement, move to next milestone!

**Comment by stefandesu** [comment]
I quickly tried to implement this because the algorithm to determine the previous concept is very easy, BUT there is one issue, maybe you have an idea how to go around this: If the previous child (relative to the current concept) has children, the previous button should point to its last child. But generally, its children aren't even loaded yet, we just know that there are children, but not how many or which ones. So in this case, the previous concept can't be determined.

We could add a piece of code that loads the previous child's children whenever a concept is selected. That would add a tiny bit of overhead, but shouldn't be too bad. What do you think?

**Comment by nichtich** [comment]
Would triggering the loading only when prev-button is activated work?

**Comment by stefandesu** [comment]
> Would triggering the loading only when prev-button is activated work?

Do you mean when the button is clicked? You can activate or deactivate the button.

Edit: That would be possible, but add a little bit of complexity to the issue.

**Comment by nichtich** [comment]
Better no additional complexity nor speed penalty for such an issue. Maybe complexity can be reduced by general refactoring, e.g. #74.

**Comment by stefandesu** [comment]
Either way, there will be added complexity to this issue because refactoring does not change the underlying problem that the children of previous concepts might not be loaded yet.

**Comment by stefandesu** [comment]
So with #505, I could easily add the prevButton for lists without hierarchy, like favorite concepts or custom lists. The problem with unknown children still exists for lists with a hierarchy. Should we add the prevButton for flat lists?

**Comment by nichtich** [comment]
Yes, support for flat lists should be enough to start with and to close this issue.
