### ISSUE TITLE
Stop polling when application is in background

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#509]
See https://webkit.org/blog/8970/how-web-content-can-affect-power-usage/ for reason. If the application is in background, pause polling for new mappings in mapping search and mapping navigator.

**Comment by stefandesu** [comment]
Good article. Not that Cocoda is supposed to be used for serious work on small laptops where power usage matters, but I still agree that at least when in the background, we should stop any activity and schedule it to update when the application is back in foreground.

In general, I'd like to refactor API requests and background activity anyway because I feel that the application could be MUCH faster than it currently is, even with lots of network requests that are needed.

**Comment by stefandesu** [comment]
See also: https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

**Comment by stefandesu** [comment]
Depends on #536.

**Comment by stefandesu** [comment]
As far as I can see, only MappingBrowser and App.vue do stuff in the background (which is repeatedly loading mappings and buildInfo.json repectively), and I now utilized the Page Visibility API to pause those tasks whenever the page goes into the background (and unpause when the page becomes visible again). I implemented this as a mixin, so if any other components do something similar, it can easily be implemented there as well.
