### ISSUE TITLE
Highlight selected concepts

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#51]
The selected concept is highlighted in ConceptTree with blue background. It should highlighted similar in MappingBrowser. Occurrences Browser, and maybe MappingEditor.

**Comment by stefandesu** [comment]
Here are a couple of suggestions:

1. The badge and text of the selected concept are in blue and the text is bold. This is applied everywhere, even in the tree:
<img width="1653" alt="screen shot 2018-06-15 at 14 26 03" src="https://user-images.githubusercontent.com/3275148/41468683-1ae2e1f2-70ab-11e8-8f73-857f64e43e66.png">

2. The current style of the selected concept in the concept tree (blue background, light and bold text) is applied everywhere. Note that this would of course not be the final version, there would be adjustments to be made:
<img width="1651" alt="screen shot 2018-06-15 at 14 35 44" src="https://user-images.githubusercontent.com/3275148/41468821-81268ac2-70ab-11e8-9745-fd37eac41758.png">

3. Like 1., except that the style in the concept tree stays original:
<img width="1653" alt="screen shot 2018-06-15 at 14 40 13" src="https://user-images.githubusercontent.com/3275148/41468844-93c1ca66-70ab-11e8-8c1f-34e752c6b5fc.png">

4. Like 1., except that there is a lighter blue background color in the concept tree. Not shown on the image is that the hover color in the concept tree was changed to the yellow, like the hover color of all buttons and badges everywhere else.
<img width="1652" alt="screen shot 2018-06-15 at 14 46 05" src="https://user-images.githubusercontent.com/3275148/41468910-c2e8ea68-70ab-11e8-8c3f-09b1547fd6c9.png">

My personal opinion:
1. Just a different badge color and text may be enough to highlight the selected concept in other components, but in the concept tree it is hard to spot the selected concept quickly, especially when scrolling through the tree. 
2. Having a blue background works in the concept tree, but certainly not anywhere else. Even if we'd improve the appearance of it, it would still look out of place. Definitely my least favorite option.
3. Probably the "cleanest" solution, but there is no real consistency between the selected concept in the tree and everywhere else. 
4. My preferred option. We have consistency (the selected concept always has a blue badge and blue and bold text), but the selected concept is still easy to spot in the concept tree due to the background color. 

What do you say?

**Comment by nichtich** [comment]
Option 4 looks best. We can then later experiment with different layouts (e.g. different color)

**Comment by stefandesu** [comment]
Option 4 is now on dev.
