### ISSUE TITLE
MappingBrowser: remove table header

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#510]
The table header ("From", "To") can be removed. It only takes up space and does not explain all table columns anyway.

**Comment by stefandesu** [comment]
So, we've been back and forth on this the past 1 1/2 years, and I think the table header should stay. It is not only "From" and "To", but also "Creator" and "Date", and the "Link" button to get a link to the current search is also on the same row. I kind of agree that we wouldn't lose much if we removed it, but then we'd need to find a new position for the "Link" button, and to gain a few pixels in vertical space isn't that important I think.

Feel free to convince me otherwise, especially by providing a new space where we can put the "Link" button. ;)

**Comment by nichtich** [comment]
Ok please remember me we discussed this before, the next time I'll bring it up!
