### ISSUE TITLE
RVK instance sometimes shows no mapping editor

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#514]
Several users had an empty Mapping Editor at <https://coli-conc.gbv.de/cocoda/rvk/>. Spotted at least on Windows with Firefox but not always. May be related to #513

**Comment by stefandesu** [comment]
Happens to me in Firefox as well. I don't think it has anything to do with #513 though, I see a lot of error message on the console that look like there's something wrong with the configuration. I think I can figure it out.

**Comment by stefandesu** [comment]
This should be fixed now. The bug happened where the user has not selected a mapping registry and was also not authorized to save into any mapping registry. This hasn't happened before because we also had local mappings, so the fallback for the getter for the current mapping registry worked. For now, I adjusted the fallback to use any registry which allows saving mappings even if the user is currently not authorized.

This should be fixed properly at some point, see #515.
