### ISSUE TITLE
Create ConceptSchemeDetail component

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#52]
Information about a ConceptScheme is shown in ConceptDetail only when a new scheme has been selected. This should be an independent and additional component. It could be toggled on with a small (i) icon next to the name of the current concept scheme in concept scheme selection.

**Comment by stefandesu** [comment]
Do we really need a separate component for this? Couldn't we just show another instance of ConceptDetail for the scheme if the (i) is clicked?

If we create a separate component for this, should ConceptDetail even support schemes? (probably not) After selecting a scheme, should ConceptDetail show a "please select a concept" message or should the ConceptSchemeDetail component be shown in its place (i.e. the current behavior stays, but ConceptSchemeDetail is a separate component and can be shown with the (i) as well)?

**Comment by nichtich** [comment]
Concept and Concept Schemes require differnt kind of layout and details so two components make sense. Support of schemes for ConceptDetail should be dropped then. I thought the instance of ConceptSchemeDetail to be shown in addition to ConceptDetail as they can be minimized.

**Comment by stefandesu** [comment]
Okay, I'll make a suggestion and we'll see from there.

**Comment by stefandesu** [comment]
I think it would be useful to have another component that is above the actual detail components in the hierarchy, for example:

ItemDetail
-> SchemeDetail
-> ConceptDetail

ItemDetail could receive either a concept or a scheme and decides which child component to use according to that. ItemDetail could also be responsible for loading the detailed information because it's the same API request for both concepts and schemes. Basically it would be enough to pass a URI to ItemDetail and it would do the rest (although I'd suggest using objects to retain reactivity in Vue, so if only the URI is available, you could pass { uri: "..." } to ItemDetail). 

Does that sound reasonable?
