### ISSUE TITLE
Support decomposing compound concepts

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#524]
Both RVK and DDC support compound concepts. Concept Details should contain a tab to display which components a compound concept is build from. See https://coli-conc.gbv.de/coli-ana/ for a draft. This requires an additional web-service to query concept components for concepts of selected concept schemes.

**Comment by nichtich** [comment]
In K10plus decomposed DDC can be put into [045H/00](https://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=5400&katalog=Standard), e.g. [this record](https://opac.k10plus.de/DB=2.299/PPNSET?PPN=1688479732&PRS=PP):

~~~pica
045F $e23$a700.9044
~~~

could get in addition:

~~~pica
045H/00 $e23$a700.9044$c700$f09044
~~~

Which in JSKOS is

~~~json
{
  "notation": [ "700.9044" ],
  "memberList": [
    { "uri": "http://dewey.info/class/700/e23/", "notation": "700" },
    { "uri": "http://dewey.info/class/1--09044/e23/", "notation": "T1--09044" }
  ]
}
~~~

**Comment by nichtich** [comment]
See <https://github.com/gbv/coli-ana-api> for a draft of an API to be included in Cocoda.

**Comment by stefandesu** [comment]
Since the coli-ana API is now available (see https://github.com/gbv/coli-ana and https://coli-conc.gbv.de/coli-ana/app/), we could integrate it into Cocoda. I'm going to try and implement a basic interface. I wouldn't offer everything that the coli-ana interface offers, but rather link to it for a full analysis.

**Comment by stefandesu** [comment]
There's a first implementation in dev, see https://coli-conc.gbv.de/cocoda/dev/?fromScheme=http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F241&from=http%3A%2F%2Fdewey.info%2Fclass%2F103.02938764%2Fe23%2F for example.

Things missing:
- Localization of interface text.
- Note in case of incomplete analysis.
- Maybe API links?
- Deal with languages: Currently, if for some of the members in the analysis list there are English labels and the interface is in English, then those will be shown in English as well. That's probably how it should be, but then we should also load labels for the other members so that they are uniform in one language, if possible. (But for DDC specifically, this issue is even more complicated.)

**Comment by stefandesu** [comment]
After we fix the issues with our CI, I suggest to release a new patch version with the current implementation of this. However, all the issues above should be fixed in a future update.

**Comment by stefandesu** [comment]
The current implementation is now published with version [1.4.5](https://github.com/gbv/cocoda/releases/tag/1.4.5). Since there's still some things to do, I will leave this issue open.

**Comment by stefandesu** [comment]
I just added a few improvements to the feature, including one that wasn't mentioned before: In certain cases (no concept information available => likely a custom built number and not part of the standard tables), the coli-ana tab is activated automatically.

Example: https://coli-conc.gbv.de/cocoda/dev/?fromScheme=http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F241&from=http%3A%2F%2Fdewey.info%2Fclass%2F001.09409%2Fe23%2F

I would suggest releasing another patch version with these changes as the last release before refactoring Cocoda to Vue 3.

**Comment by stefandesu** [comment]
There's still a bug: Second notations will not be saved correctly if the same concept was already loaded before as part of another analysis. For example, first open the analysis for `700.90440747471`, then for `001.09409`. Some concepts will have a much longer second notation that is applicable in this case.

The reason for this is that the concepts will be saved like every other concept, and once `notation[1]` is set, it won't be changed. Instead, the `memberList` of concepts should be kept independent of the other concepts. This, however, makes loading concept data a bit more difficult.

Edit: Fixed.
