### ISSUE TITLE
Create UserSettings component

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#53]
Users want to store setting such as language, identity provider, default layout etc. This requires #15 and a backend service to store settings (although settings could also be stored as cookies).

**Comment by stefandesu** [comment]
I would suggest using Local Storage instead of cookies. First of all, settings are only needed client-side and that's what local storage is for. Also, it would give users the option to keep their settings without logging in (some might not want to), and it would relieve us from adding a cookie popup for all users (since we'd only store a cookie when the user decides to log in).

**Comment by stefandesu** [comment]
Settings now implemented in local storage.
