### ISSUE TITLE
My Own Taxonomies?

### ISSUE THREAD

**Issue by martinherzog** [gbv/cocoda#578]
Dear Cocoda Team!

I was looking for an online Ontology mapping tool just like this. Is it possible to extend the use case and map my own Ontologies, or KOS with it. For example some OWL or RDFS vocabularies that I have created on my own during my research projects... 

So basically, Is there a way to upload individually customized Ontologies into Cocoda and map them? 

Cheers,
Martin

**Comment by stefandesu** [comment]
Dear Martin,

Thanks for showing interest in Cocoda! It's definitely possible to get your own KOS into Cocoda. In general, there are two main ways to do this:

1. Provide your data to us and we'll host it in our public instance of the backend (https://coli-conc.gbv.de/api/). In this case, you could just use our Cocoda instance to create the mappings. (Note that both your KOS and your mappings would be publicly available in this case.)

2. Host your own instance of [jskos-server](https://github.com/gbv/jskos-server) and import your data there. You could then use it to store your mappings as well. If your KOS and mappings are not of public interest, this would probably be the way to go.

Some further notes:
- In either case, it will be necessary to convert your KOS into the [JSKOS format](https://gbv.github.io/jskos/jskos.html). Unfortunately, our documentation and tools about conversion are still lacking. @nichtich is usually the one who deals with this, so I'm sure he'll be able and willing to help.
- If you were to go with option 2, I'm planning to make it much easier to host your own instance of jskos-server by adding Docker images, and also improve the import scripts that are used to get your data into jskos-server. Cocoda itself and [login-server](https://github.com/gbv/login-server) (our authentication backend) already have Docker images, so as soon as jskos-server has them as well, it will be very easy to set up your own infrastructure for hosting your vocabularies and create mappings via Cocoda. If you would like to get started sooner (I'm currently focused on another thing, but these changes are the next thing on my list), I'm definitely willing to help you out with self-hosting it the "old way". (Just a heads-up: I won't be available for most of next week, so there might be some delays with the responses.)
- There is an undocumented way of using our public Cocoda instance with your own instance of jskos-server, by using the `config` parameter to supply a configuration file. (I once created a [repo](https://github.com/stefandesu/cocoda-configs) demonstrating this, ~~but the examples don't seem to work. I guess the functionality might be broken because it wasn't really used anyway. 🙈~~ Edit: It was a CORS issue. I updated both Cocoda on dev with a quick fix and my repo with fixed example links.)

Anyway, it's exciting to have some outside interest in our project! Please let us know if you have further questions or need assistance with setting everything up. If you notice that parts of our documentation is insufficient, let us know as well. 🙂

Best,
Stefan

**Comment by nichtich** [comment]
I've added a section at <https://github.com/gbv/cocoda/wiki/FAQ#how-to-import-new-vocabularies>. There is no generic converter from RDFS and OWL ontologies to JSKOS but this may be of use for others too (https://github.com/gbv/jskos-cli/issues/13).

**Comment by martinherzog** [comment]
Dear Stefan,

thanks a lot for your help! I'm glad there is a possibility, especially for managing an own private instance of Cocoda. This will most likely be the way to go for our project. I will look into in more detail and try to setup a jskos-server sometime soon. However, I'm not in a hurry for this, so I guess I will wait for those docker images you are mentioning and keep an eye on this thread!

Thank you also for the pointers regarding conversion from OWL/RDFS into JSKOS. 

Best, 
Martin

**Comment by stefandesu** [comment]
I'll let you know here. You can be our first guinea pig with the Docker stuff to see whether our documentation is good enough. 😁

**Comment by stefandesu** [comment]
Dear Martin, I've decided that I will add Docker support for jskos-server before some other, more complicated changes that we originally planned to launch at the same time. Due to my absence next week, I won't be able to implement it then, but in the week after I should be able to do it and release a new version. I'll also start a document which offers step-by-step instructions on how to set up the whole infrastructure with Docker. I'll let you know as soon as I have more!

**Comment by stefandesu** [comment]
Dear Martin,

I finally added Docker support for jskos-server and wrote a first guide on how to set up Cocoda, jskos-server, and login-server with Docker Compose: https://github.com/gbv/coli-conc-docker

Please let me know if it works for you and if you have suggestion on how to improve it. Thanks!

**Comment by martinherzog** [comment]
Dear Stafan, 
thank you for the update! Right now, I am in the middle of another project. I will let you know once I find the time to look into it again. Cheers.

**Comment by stefandesu** [comment]
Sure, just get back to me if you have any questions of feedback! For now, I'll close this issue.
