### ISSUE TITLE
Mapping search: filter by annotation

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#605]
Support searching for annotated mappings. This is already [supported by JSKOS server](https://github.com/gbv/jskos-server#get-mappings) (`annotatedFor` and `annotatedWith`)

**Comment by stefandesu** [comment]
It would be nice to also have a filter whether the total rating of a mapping is positive or negative (see #666).

**Comment by stefandesu** [comment]
This requires some changes in jskos-server (if we want the total rating) and I would also deal with #671 first, so I'm moving this to the next milestone.

**Comment by stefandesu** [comment]
This is now pretty much done from my point of view and it works well locally as well as with the Dev Registry in Cocoda Dev. To work with the main registry, we need a release of JSKOS Server. I will do some more testing before closing this.

**Comment by stefandesu** [comment]
@nichtich Currently we have all available options that JSKOS Server offers in the interface. That is:

- any
- none
- assessed (-1/+1)
- assessed (+1)
- assessed (-1)
- not assessed
- confirmed
- not confirmed

There was already some confusion because the filter is called "assessment", so the differentiation between "none" and "not assessed" was not clear. However, I would like to avoid too technical terms in the interface.

I'm personally not sure whether "any" is even needed. My suggestion would be to remove "any", and rename "none" to "neither assessed nor confirmed" and move it to the bottom of the list. What do you think?

**Comment by nichtich** [comment]
> I'm personally not sure whether "any" is even needed. My suggestion would be to remove "any", and rename "none" to "neither assessed nor confirmed" and move it to the bottom of the list. What do you think?

In general I agree but I am not sure about the position, how do you clear the filter?

**Comment by stefandesu** [comment]
It works exactly like any of the other filters (mapping type, cardinality, concordance). I didn't change anything about how search filters work in general. So I'm not sure what you mean. (You clear the filter either by selecting "-" as an option or clicking the "Clear" button.)

Improvements to the search filters in general will come later in #671. This issue is only about this particular filter.

**Comment by nichtich** [comment]
ok, implement as proposed without "any".
