### ISSUE TITLE
Support larger jumps in pagination

### ISSUE THREAD

**Issue by schuchaa** [gbv/cocoda#609]
so far it is only possible to jump page by page or all the way to the end (https://coli-conc.gbv.de/cocoda/app/). This is a very slow way when looking at many concordances. It would be very helpful to be able to skip two to three pages.

**Comment by nichtich** [comment]
Link to previous and next page are duplicated: you can click either on the `<`/`>` or on the number. Maybe change `<` and `>` to skip some pages? If we make it to go to *half* of the pages between current and start/end, the links could be used for binary search :-)

**Comment by stefandesu** [comment]
You are right, but isn't this the default for pagination like this? Also, I don't think I can differentiate between the user clicking on `2` or the user clicking on `>` because the bootstrap pagination component simply emits the new page number.

To be honest though, I don't really know how to fix this elegantly. How is it done elsewhere? I've suggested a "go to page" button, but it's kind of clunky and requires a UI for something so small.

**Comment by nichtich** [comment]
Wontfix if it's too complex. Alternatively think how to simplify changing "results per page" number. This issue first requires some user feedback.

**Comment by stefandesu** [comment]
There is now a "go to page" button (see #387).
