### ISSUE TITLE
Implementation of a comment function with annotations

### ISSUE THREAD

**Issue by schuchaa** [gbv/cocoda#610]
For the creation of mappings it is useful to be able to assign comments. For example, for comments from the WebDewey Deutsch that have led to a mapping decision.

**Comment by stefandesu** [comment]
As far as I can see, this should already be supported by jskos-server because it doesn't restrict the `motivation` property of annotations. However, there are related issues that could be addressed:
- https://github.com/gbv/jskos-server/issues/147 
- https://github.com/gbv/jskos-server/issues/41

So this issue is only about the UI implementation in Cocoda. Should we allow any markup (maybe a restricted set of Markdown) or just plain text?

**Comment by nichtich** [comment]
just plain text. Could also include hyperlinks (clients can detect "https?://..." URLs and provide as link).

**Comment by nichtich** [comment]
Includes at least

* [ ] show comments in mapping detail
* [ ] indicate existing comments in mapping table (e.g. with a colored [speech bubble](https://favicon.io/emoji-favicons/left-speech-bubble/))
* [ ] edit form to add or delete a comment (also to modify?)

A plain comment is not enough nevertheless. What's the typical workflow?

* Some comments are additional explanation to a mapping
* Some comments are questions or remarks to change, add, improve... something related to the mapping. These comments should be removed after the issue has been resolved.

For the second use case comments are like GitHub issues or word processor edit suggestions, so the workflow is

* mapping is commented by person A
* comment is deleted ("resolved") by person B

Who should be allowed to delete/resolve comments? Any of:

* account with rights to edit the commented mapping
* account with rights to confirm the mapping
* the creator of the comment

**Comment by nichtich** [comment]
We
