### ISSUE TITLE
Add RVK search links

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#611]
To quickly look up which publications have been indexed with a RVK notation:

* K10plus: https://opac.k10plus.de/DB=2.299/CLK?IKT=3002&NOABS=Y&TRM={notation}
* SWB: https://swb.bsz-bw.de/DB=2.1/CMD?ACT=SRCHA&IKT=3002&TRM={notation}
* Bibliotheksverbund Bayern (BVB):  https://bvbat01.bib-bvb.de/TP61/start.do?Query=0080%3D%22{notation}%22+IN+%5B1%5D
* Österreichischer Bibliothekenverbund (OBV): https://search.obvsg.at/primo-explore/search?vid=OBV&query=lsr06%2Cexact%2C{notation}%2CAND&mode=advanced

**Comment by stefandesu** [comment]
These can be added to an instance via the `searchLinks` config field, so it does not require a new version. However, we could add them to the default config as well.

**Comment by nichtich** [comment]
Ok do both an then hope for #565 (requires https://github.com/gbv/bartoc.org/issues/76) because management o f these links better belongs into BARTOC.

**Comment by stefandesu** [comment]
I found out that the `searchLinks` config field was not merged, so specifying custom search links would override all default search links. I have now changed this behavior (in e140b6e05c0a155f98c7c8243db10012dd5de49f) and also added the above search links to the default config.

Since it looks like we're going to create one more small release soon, this change will be included then.

I agree that in the future, scheme-specific search links could be added in BARTOC.
