### ISSUE TITLE
MappingNavigator: remove visual clutter by opiniated settings

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#639]
Opinionated settings to remove number of setting and visual clutter:

* Currently selected mapping database alway at the top
* Never show empty sections

 The only reason is to show empty sections is to allow selection of mapping database. This could also be done via dropdown at the selected registry name (both in mapping navigator and in mapping editor) or via the icons used to hide individual registries (maybe three states: show, hide, select).

**Comment by stefandesu** [comment]
> The only reason is to show empty sections is to allow selection of mapping database.

I disagree. Especially for beginners, I think it is extremely helpful to see that there is a data source which *could* provide mappings, but that simply doesn't have any results for the current search. Also, we would then need to differentiate between no results and an error loading the mappings. If we remove the setting, I'd rather have the default be to always show empty sections. (To be honest, I'm not super sure how it is currently handled if a section is empty but there was an error if "show empty sections" is turned off.)

> Currently selected mapping database alway at the top

I don't care much about this either way, so we can this.

**Comment by stefandesu** [comment]
I thought this was something that we could easily implement for 1.5.0 and chose to go for:
- Always show selected mapping database at the top (probably no discussion here).
- Always show empty sections.

I'm open for further discussion on the latter point, but here is my reasoning again:
- It's confusing to the user if a whole section disappears just because there are no results.
- I also added a text "no results" to make it a bit clearer.
- If there's an error with the registry, it will also be shown there.

If you look at the commit diffs for those changes, you'll also see that these two preferences involved basically no code. It was just one if condition. So we could also easily revert the changes if we can't decide how we want to deal with it at the moment.
