### ISSUE TITLE
Show catalog enrichment based on a mapping

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#641]
Given a mapping we can query the number of title records enriched based on this mapping in K10plus. This information should somehow be shown in Cocoda.

Simple solution: Add an URL in mapping details modal such as https://opac.k10plus.de/DB=2.299/CMD?ACT=SRCHA&IKT=8659&TRM=https+coli+conc+gbv+de+api+mappings+5812d5a4+4301+4677+9236+e6e3b8d68f24 (note that all sequences of non-alphanumerical characters must be replaced with space, resulting in `+`) with label "search enrichment in K10plus" = "Anreicherung im K10plus suchen".

Better solution (maybe later): query an API whether and how many titles have been enriched and directly show indicator at the mapping.

**Comment by stefandesu** [comment]
For replacing non-alphanumerical characters, we can use `uri.replace(/[\W_]+/g,"+")` (see [here](https://stackoverflow.com/a/20864946/11050851)). I can try to implement this now.

**Comment by stefandesu** [comment]
Link is implemented in Dev. Please create a separate issue if necessary for requesting the number of enrichments via an API. (Although I'd recommend reconsidering this because the cost of all those requests might be too high. Maybe it's possible to make it more efficient by requesting multiple mappings at once, adding the data directly to our mapping database, or only request the data to be shown in the MappingDetail component.)
