### ISSUE TITLE
Extend MappingEditor to assign mappings to concordances

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#652]
*This issue is part of #623*

MappingEditor should provide a field to assign or remove a mapping to a concordance.

* Each mapping is only assigned one concordance at most.
* The list of possible concordances is all concordances that
  * have `fromScheme`/`toScheme` referencing the same vocabularies as `fromScheme` `toScheme`of the mapping
  * have currently logged in user listed in `creator` or `contributor`

**Comment by stefandesu** [comment]
It would make sense to show the mapping's concordance in the bottom right of MappingEditor (since we removed the creator name and there is now some space left). I think there are two possibilities for implementation:

1. Have a dropdown/select tag right there which shows all possible concordances and lets the user select the concordance for the mapping. This is the easiest implementation, but might not look very nice.
2. Only show the name of the concordance (or "no concordance" if none is assigned) and on hover, show a popover where the concordance can be changed.

I think we should explore the first option for now, and if we can't get it to look right, then fall back to the more complex interface with a popover.

**Comment by stefandesu** [comment]
First implementation now done in https://github.com/gbv/cocoda/commit/1e61057517a745be12fe2a5301bb41873637504f. Will close this issue after some testing.

**Comment by stefandesu** [comment]
With https://github.com/gbv/cocoda/commit/8be0437e63e12b1f70724c6cdc7fb569ef4041dd, Cocoda now remembers the last used concordance in MappingEditor and uses it if possible (i.e. if vocabularies match). It will not remember this after the site is reloaded, but I think that is okay for now.
