### ISSUE TITLE
Don't select concept if already selected

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#71]
If a concept is clicked in Occurrences Browser or Mapping Browser, it is loaded in the Concept Tree and Concept Details. Reloading should be skipped if the concept is already the currently selected - but the Concept Tree should still scroll to the concept.

**Comment by stefandesu** [comment]
As of yesterday with the introduction of a new API access layer (especially 928eaf3f7335563d10af4d9f64f0f4c383fbbe53), this is not an issue anymore. Although it is not explicitly checked whether the concept was already selected before, no further API requests will be made because all the necessary data was already loaded before.
